apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: mqtt
        image: lafelx/h-mqtt-service:latest
        resources:
          limits:
            memory: 256Mi 
            cpu: '0.2'
        ports:
        - containerPort: 1883
        env:
          - name: rabbitmq_secret
            valueFrom:
              secretKeyRef:
                key: secret
                name: rabbitmq-access-secret
