apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./k8s/identityTlsCertificate.yaml"
  - "./k8s/selfsignedIssuer.yaml"
  - "./k8s/infrastructure/postgres"
  - "./k8s/infrastructure/ingress"
  - "./k8s/infrastructure/rabbitmq"
  - "./IdentityService"
  - "./ProvisionService"
  - "./MqttService"
  - "./ClientSpa"
  - "./TempSpa"
