apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-tls-certificate
spec:
  secretName: identity-tls-certificate
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - Hubertyne
  commonName: Hubertyne host # TODO: Change to actual IP or domain
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - localhost # Change to actual IP or domain
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io

