apiVersion: apps/v1
kind: Deployment
metadata:
  name: plug
  labels:
    app: plug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plug
  template:
    metadata:
      labels:
        app: plug
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: plug
        image: lafelx/h-plug-service:latest
        resources:
          limits:
            memory: 256Mi 
            cpu: '0.2'
        ports:
        - containerPort: 1883
        env:
          - name: db_host_string
            valueFrom:
              secretKeyRef:
                key: db_host_string
                name: postgres-access-secret
          - name: rabbitmq_secret
            valueFrom:
              secretKeyRef:
                key: secret
                name: rabbitmq-access-secret
