apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-insecure-ingress
  labels:
    name: nginx-insecure-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: connect.hubertyne.me
      http:
        paths:
          - backend:
              service:
                name: addplug-spa
                port:
                  number: 80
            pathType: Prefix
            path: /

