apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-main-ingress
  labels:
    name: nginx-main-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/issuer: "selfsigned-issuer"
spec:
  tls:
    - hosts:
        - "identity.localhost"
      secretName: identity-certificate
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: provision
                port:
                  number: 80
            pathType: Prefix
            path: /
    - host: dashboard.localhost
      http:
        paths:
          - backend:
              service:
                name: identity-spa
                port:
                  number: 80
            pathType: Prefix
            path: /
    - host: identity.localhost
      http:
        paths:
          - pathType: Prefix
            path: /.well-known
            backend:
              service:
                name: identity
                port:
                  number: 80
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: identity
                port:
                  number: 80
          - pathType: Prefix
            path: /connect
            backend:
              service:
                name: identity
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-spa
                port:
                  number: 80
