apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-main-ingress
  labels:
    name: nginx-main-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - "identity.hubertyne.me"
        - "www.hubertyne.me"
        - "api.hubertyne.me"
      secretName: production-certificate
  ingressClassName: nginx
  rules:
    - host: api.hubertyne.me
      http:
        paths:
          - backend:
              service:
                name: provision
                port:
                  number: 80
            pathType: Prefix
            path: /api/provisions
          - backend:
              service:
                name: plug
                port:
                  number: 80
            pathType: Prefix
            path: /api/plug
    - host: www.hubertyne.me
      http:
        paths:
          - backend:
              service:
                name: client-spa
                port:
                  number: 80
            pathType: Prefix
            path: /
    - host: identity.hubertyne.me
      http:
        paths:
          - pathType: Prefix
            path: /.well-known
            backend:
              service:
                name: identity
                port:
                  number: 80
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: identity
                port:
                  number: 80
          - pathType: Prefix
            path: /connect
            backend:
              service:
                name: identity
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-spa
                port:
                  number: 80
