apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: postgres
        image: postgres:15
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: '0.1'
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: secret
                name: postgres-access-secret
        ports:
          - containerPort: 5432
