apiVersion: apps/v1
kind: Deployment
metadata:
  name: addplug-spa
  labels:
    app: addplug-spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addplug-spa
  template:
    metadata:
      labels:
        app: addplug-spa
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: mqtt
        image: lafelx/h-addplug-spa
        resources:
          limits:
            memory: 512Mi 
            cpu: "1"
        ports:
        - containerPort: 1883
        env:
          - name: rabbitmq_secret
            valueFrom:
              secretKeyRef:
                key: secret
                name: rabbitmq-access-secret
