apiVersion: apps/v1
kind: Deployment
metadata:
  name: provision
  labels:
    app: provision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provision
  template:
    metadata:
      labels:
        app: provision
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: provision
        image: p-server
        imagePullPolicy: Never
        resources:
          limits:
            memory: 512Mi 
            cpu: "1"
        ports:
        - containerPort: 80
        env:
          - name: db_host_string
            valueFrom:
              secretKeyRef:
                key: db_host_string
                name: postgres-access-secret
          - name: rabbitmq_secret
            valueFrom:
              secretKeyRef:
                key: secret
                name: rabbitmq-access-secret
