apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-spa
spec:
  selector:
    matchLabels:
      app: client-spa
  template:
    metadata:
      labels:
        app: client-spa
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: client-spa
          image: lafelx/h-client-spa:latest
          resources:
            limits:
              memory: '256Mi'
              cpu: '0.1'
          ports:
            - containerPort: 80
