apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: id-server
        imagePullPolicy: Never
        resources:
          limits:
            memory: 512Mi 
            cpu: "1"
        ports:
        - containerPort: 80
        env:
          - name: db_host_string
            valueFrom:
              secretKeyRef:
                key: db_host_string
                name: postgres-access-secret
