apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: identity
        image: lafelx/h-identity-service:latest
        resources:
          limits:
            memory: 256Mi 
            cpu: '0.2'
        ports:
        - containerPort: 80
        env:
          - name: db_host_string
            valueFrom:
              secretKeyRef:
                key: db_host_string
                name: postgres-access-secret
