name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    environment: staging
    strategy:
      matrix:
        include:
          - dockerfile: ./PlugService/Dockerfile
            image: lafelx/h-plug-service
            context: .
          - dockerfile: ./ProvisionService/Dockerfile
            image: lafelx/h-provision-service
            context: .
          - dockerfile: ./IdentityService/Dockerfile
            image: lafelx/h-identity-service
            context: ./IdentityService
          - dockerfile: ./MqttService/Dockerfile
            image: lafelx/h-mqtt-service
            context: .
          - dockerfile: ./IdentitySpa/Dockerfile
            image: lafelx/h-identity-spa
            context: ./IdentitySpa
          - dockerfile: ./ClientSpa/Dockerfile
            image: lafelx/h-client-spa
            context: ./ClientSpa
          - dockerfile: ./AddPlugSpa/Dockerfile
            image: lafelx/h-addplug-spa
            context: ./AddPlugSpa
        
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:latest
